# Generated by Django 3.0.6 on 2020-06-14 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='teamfeed',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='teamfeed',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Team'),
        ),
        migrations.AddField(
            model_name='moodboardfeed',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='moodboardfeed',
            name='moodboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.MoodBoard'),
        ),
        migrations.AddField(
            model_name='like',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='feedtexttool',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='feedtexttool',
            name='text_tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.TextTool'),
        ),
        migrations.AddField(
            model_name='feedimagetool',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='feedimagetool',
            name='image_tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.ImageTool'),
        ),
        migrations.AddField(
            model_name='feedhashtag',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='feedhashtag',
            name='hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.HashTag'),
        ),
        migrations.AddField(
            model_name='feedfield',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='feedfield',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Field'),
        ),
        migrations.AddField(
            model_name='feed',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Color'),
        ),
        migrations.AddField(
            model_name='feed',
            name='commenter',
            field=models.ManyToManyField(related_name='commenter_feed', through='feed.Comment', to='user.User'),
        ),
        migrations.AddField(
            model_name='feed',
            name='field',
            field=models.ManyToManyField(through='feed.FeedField', to='feed.Field'),
        ),
        migrations.AddField(
            model_name='feed',
            name='image_tool',
            field=models.ManyToManyField(through='feed.FeedImageTool', to='feed.ImageTool'),
        ),
        migrations.AddField(
            model_name='feed',
            name='liker',
            field=models.ManyToManyField(related_name='liker_feed', through='feed.Like', to='user.User'),
        ),
        migrations.AddField(
            model_name='feed',
            name='moodboard',
            field=models.ManyToManyField(through='feed.MoodBoardFeed', to='user.MoodBoard'),
        ),
        migrations.AddField(
            model_name='feed',
            name='owner',
            field=models.ManyToManyField(related_name='owner_feed', through='feed.UserFeed', to='user.User'),
        ),
        migrations.AddField(
            model_name='feed',
            name='tag',
            field=models.ManyToManyField(related_name='tagged_feed', through='feed.FeedHashTag', to='feed.HashTag'),
        ),
        migrations.AddField(
            model_name='feed',
            name='team',
            field=models.ManyToManyField(through='feed.TeamFeed', to='user.Team'),
        ),
        migrations.AddField(
            model_name='feed',
            name='text_tool',
            field=models.ManyToManyField(through='feed.FeedTextTool', to='feed.TextTool'),
        ),
        migrations.AddField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
