# Generated by Django 3.0.6 on 2020-06-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200614_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_main',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='field',
            name='related_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='feed.Field'),
        ),
    ]
