# Generated by Django 3.0.6 on 2020-06-14 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'aboutme',
            },
        ),
        migrations.CreateModel(
            name='FollowField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'follow_fields',
            },
        ),
        migrations.CreateModel(
            name='FollowMoodBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'follow_moodboards',
            },
        ),
        migrations.CreateModel(
            name='FollowTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'follow_teams',
            },
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'follow_users',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45, null=True)),
                ('city', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='MoodBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'moodboards',
            },
        ),
        migrations.CreateModel(
            name='MoodBoardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('moodboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.MoodBoard')),
            ],
            options={
                'db_table': 'moodboards_users',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'social_media_links',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('team_url', models.CharField(max_length=1000)),
                ('invite_only', models.BooleanField(default=False)),
                ('team_info', models.CharField(max_length=2000, null=True)),
                ('team_img_url', models.URLField(max_length=2000, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Location')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('occupation', models.CharField(max_length=45, null=True)),
                ('current_company', models.CharField(max_length=45, null=True)),
                ('my_website', models.URLField(max_length=2000, null=True)),
                ('profile_img_url', models.URLField(max_length=2000)),
                ('social_account', models.CharField(max_length=100)),
                ('about_me', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.AboutMe')),
                ('following_field', models.ManyToManyField(related_name='follower_field', through='user.FollowField', to='feed.Field')),
                ('following_moodboard', models.ManyToManyField(related_name='follower_moodboard', through='user.FollowMoodBoard', to='user.MoodBoard')),
                ('following_team', models.ManyToManyField(related_name='follower_team', through='user.FollowTeam', to='user.Team')),
                ('following_user', models.ManyToManyField(related_name='_user_following_user_+', through='user.FollowUser', to='user.User')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Location')),
                ('moodboard', models.ManyToManyField(related_name='owner', through='user.MoodBoardUser', to='user.MoodBoard')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=45, null=True)),
                ('company_url', models.URLField(max_length=2000, null=True)),
                ('position', models.CharField(max_length=45, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('detail', models.CharField(max_length=2000, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Location')),
            ],
            options={
                'db_table': 'work_experiences',
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'users_teams',
            },
        ),
        migrations.CreateModel(
            name='UserSocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000, null=True)),
                ('social_media_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.SocialMediaLink')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'users_social_media_links',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='social_media_link',
            field=models.ManyToManyField(through='user.UserSocialMediaLink', to='user.SocialMediaLink'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(related_name='member', through='user.UserTeam', to='user.Team'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.WorkExperience'),
        ),
        migrations.CreateModel(
            name='TeamSocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.SocialMediaLink')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Team')),
            ],
            options={
                'db_table': 'teams_social_media_links',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='social_media_link',
            field=models.ManyToManyField(through='user.TeamSocialMediaLink', to='user.SocialMediaLink'),
        ),
        migrations.AddField(
            model_name='moodboarduser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AddField(
            model_name='followuser',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to='user.User'),
        ),
        migrations.AddField(
            model_name='followuser',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following', to='user.User'),
        ),
        migrations.AddField(
            model_name='followteam',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AddField(
            model_name='followteam',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Team'),
        ),
        migrations.AddField(
            model_name='followmoodboard',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AddField(
            model_name='followmoodboard',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.MoodBoard'),
        ),
        migrations.AddField(
            model_name='followfield',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AddField(
            model_name='followfield',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Field'),
        ),
    ]
