# Generated by Django 3.0.6 on 2020-06-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
